PA_DRAFTED = [
    '^Con.* McDa',
    '^Leo.* Drais',
    '^Aust.* Matt',
    '^Nath.* Mack',
    '^Mikk.* Rant',
    '^Matth.* Tkac',
    '^Dav.* Pastr',
    '^Brad.* Tkach',
    '^Jaso.* Roberts',
    '^Niki.* Kucher',
    '^Jack.* Hughe',
    '^Tage.* Thompson',
    '^Eli.* Petter',
    '^Cale.* Maka',
    'Alex Ovechkin',
    'Jack Eichel',
    'Sidney Crosby',
    'Mika Zibanejad',
    'J.T. Miller',
    'Tim Stutzle',
    'Kirill Kaprizov',
    'Timo Meier',
    'Mitch Marner',
]