SLEEPERS = [
    "Elias Lindholm",
    "Justin Faulk",
    "Jake Debrusk",
    "Gabriel Vilardi",
    "Pavel Buchnevich",
    "Joey Daccord",
    "Lane Hutson",
    "Valeri Nichushkin",
    "Viktor Arvidsson",
    "Jack Quinn",
    "Josh Norris",
    "JJ Peterka",
    "Dylan Cozens",
    "Bowen Byram",
    "Mikhail Sergachev",
    "Jake Sanderson",
    "Dylan Guenther",
    "Fabian Zetterlund",
    "Mason McTavish",
    "Mikael Granlund",
    "William Eklund",
    "Gabriel Landeskog",
    "Tyler Bertuzzi",
    "Daniil Miromanov",
]

QUICK_COMPARE_PLAYERS = [
    # 'Nylander',
    # 'J.T. Miller'
]

KKUPFL_PLAYERS = [
    # 'Moritz Seider',
    # 'Mark Sch.*',
    # 'Robert Thomas',
    # 'Josh Morrissey',
    # 'Mackenzie Weegar',
    # 'Werenski',
    # 'Sergachev',
    'J.*Erik.*Ek',
    'Dylan Larkin',
    'C.*Verhaeg',
    'A.* Svechnikov',
    'M.* Heiskanen',
    'Doug.* Hamilton',
    'Wyatt Johnst.*',
    # 'Erik Karlsson',
    # 'Jordan Kyrou',
    # 'Alex Debrincat',
    # 'Alex Tuch',
    'Seth Jarvis',
    'Nico Hischier',
    'Matt Barzal',
    'Travis Konecny',
]

PA_PLAYERS = [
    'Chris Kreider',
    'Vla.* Taras',
    'Trevor Zegras',
    'Tom Wilson',
    'Pierre-Luc Dubois',
    'Artturi Lehkonen',
    'Mark Stone',
    'Taylor Hall',
]
